apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "httpserver.fullname" . }}
  labels:
    {{- include "httpserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort}}
      protocol: TCP
      name: http
  selector:
    {{- include "httpserver.selectorLabels" . | nindent 4 }}
